name: Check for new releases

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for update
        id: check
        run: |
          CURRENT_HASH=$(cat .digest)
          REMOTE_HASH=$(curl -fSsL https://jagex.akamaized.net/direct6/launcher-win/alias.json | jq -r '.["launcher-win.production"]')
          if [ "$CURRENT_HASH" != "$REMOTE_HASH" ]; then
            echo "New release found!"
            echo -n "$REMOTE_HASH" > .digest
            echo "hash=$REMOTE_HASH" >> $GITHUB_OUTPUT
            echo 'new_release=true' >> $GITHUB_OUTPUT
          else
            echo "No new release found."
            echo 'new_release=false' >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Install dependencies
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        run: pip install -r requirements.txt

      - name: Generate release
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        id: generate
        env:
          HASH: ${{ steps.check.outputs.hash }}
        run: |
          OLDPWD=$(pwd)
          TMPDIR=$(mktemp -d)
          cd $TMPDIR
          python $OLDPWD/installer.py --hash $HASH -v
          cd $OLDPWD
          rm -rf $TMPDIR
          echo "VERSION=$(cat $OLDPWD/.version)" >> $GITHUB_OUTPUT
          echo "OUTPUT=$TMPDIR" >> $GITHUB_OUTPUT

      - name: Upload artifact
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        uses: actions/upload-artifact@v3
        with:
          name: launcher-${{steps.generate.outputs.version}}
          path: ${{steps.generate.outputs.output}}

      - name: Setup GPG
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Save changes to repo
        if: steps.check.outputs.new_release == 'true' && steps.check.outputs.hash != ''
        run: |
          git commit --signoff -m "Update to ${{steps.generate.outputs.version}} @ ${{steps.check.outputs.hash}}" .digest
          git push
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
